# Generated by Django 5.0.6 on 2024-07-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_balance_urls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Stream',
        ),
    ]
