# Generated by Django 5.0.6 on 2024-07-01 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_urls_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='discount',
            field=models.BigIntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
