# Generated by Django 5.0.6 on 2024-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_stream_discount_stream_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefit',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(db_default=0),
        ),
    ]
