# Generated by Django 5.0.6 on 2024-07-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_benefit_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='benefit',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='count',
            field=models.IntegerField(db_default=1),
        ),
    ]
